use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :interface, InterfaceWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: ["//heating-brain.local", "//ogrzewanie"],
  http: [:inet6, port: 80],
  live_view: [signing_salt: "PNPrVtXA/np3s/HgsrqSK+MHWhT2ldfk7KxeVz13yaaX2WRpq6MF0e/JU47AiP9h"],
  secret_key_base:
    "ceoDXVovvCIZfjEPCdEs6YJ6AKN1+xkS1vcfFZXdONT9f5koifDCPv8mMnR0lR85GRPMEDPm+cAqEgriwl2Ucz1LQrepxSB3igJuVsLY9ovVjNIAl",
  url: [host: "heating-brain.local", port: 80]

config :interface, InterfaceWeb.Endpoint, server: true
