#!/usr/bin/env bash

set -e

green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
reset=`tput sgr0`

function label() {
  echo
  echo "${green}$1${reset}"
}

function run() {
  echo "${blue}Running ${yellow}$@${reset}"
  eval $@
}

label "Building static assets"
run "npm --prefix assets install"
run "npm --prefix assets run deploy"

label "Digesting and compressing static files"
run "mix phx.digest"

label "Logging deployment"
run "ssh brain \"logger 'Deploying the Heating Brain application'\""

label "Backing up database"
run "ssh brain \"/opt/heating_brain/_build/prod/rel/heating_brain/bin/heating_brain rpc ':ok = Collector.Storage.create_backup()' || echo App is not running\""

label "Uploading files to the server"
run "rsync -rav --exclude-from=.gitignore --exclude=.git --prune-empty-dirs . brain:/opt/heating_brain"

label "Updating systemd service unit"
run "ssh brain \"sudo cp /opt/heating_brain/server/systemd/heating_brain.service /etc/systemd/system/heating_brain.service\""

label "Reloading systemd daemon"
run "ssh brain \"sudo systemctl daemon-reload\""

label "Enabling systemd service unit"
run "ssh brain \"sudo systemctl enable heating_brain\""

label "Updating version tag file"
VERSION=$(git rev-parse HEAD)
run "ssh brain \"echo $VERSION >> /opt/heating_brain/VERSION_SHA\""

label "Creating a new release"
run "ssh brain \"/opt/heating_brain/server/compile\""

label "Restarting the application"
run "ssh brain \"sudo systemctl restart heating_brain\""
